Feature/ung 2282 process poc admin
ubirch/ubirch-poc-manager pull request #82
Opened 2021-05-20 10:05 UTC by Hiroki6

2021-05-20 10:07 UTC, Hiroki6 commented on src/main/resources/db/migration/V3_0__poc_admin_table.sql
>      poc_admin_id                 UUID            NOT NULL,
I will change this table after we merge the webident implementation

2021-05-20 10:07 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/poc/CertfiyHelper.scala
> +  override def addGroupsToCertifyUser(
@lalottacontinua I want you to have a look at this part.

2021-05-20 10:07 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/teamdrive/SttpTeamDriveClient.scala
> +  override def getSpaceIdByName(spaceName: String): Task[Option[SpaceId]] = {
@gzhk I want you to have a look at this part.

2021-05-20 10:38 UTC, gzhk commented on src/main/scala/com/ubirch/services/teamdrive/SttpTeamDriveClient.scala
> +  override def getSpaceIdByName(spaceName: String): Task[Option[SpaceId]] = {
looks good to me

2021-05-20 11:08 UTC, lalottacontinua requested changes
some changes required. let's talk, if you got questions.

2021-05-20 11:08 UTC, lalottacontinua commented on src/main/scala/com/ubirch/services/teamdrive/SttpTeamDriveClient.scala
> +            val errorMsg = s"couldn't find the space name: $spaceName"
duplicating errorMsg.. ;) And why make a warn not an error log?

2021-05-20 11:08 UTC, lalottacontinua commented on src/main/scala/com/ubirch/services/poc/PocAdminCreator.scala
> +    val spaceName = s"${pocConfig.teamDriveStage}_${tenant.tenantName.value}"
Oh, and this only needs to be done, if the poc.clientCertRequired attribute is set to true. Otherwise we will provide the certificate on a tenant level.

2021-05-20 12:31 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/poc/CertfiyHelper.scala
> +        case Right(_) => pocAdminAndStatus.copy(status = pocAdminAndStatus.status.copy(certifierUserCreated = true))
Sure.

2021-05-20 12:34 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/teamdrive/SttpTeamDriveClient.scala
> +            val errorMsg = s"couldn't find the space name: $spaceName"
this method returns None, which means it's not an error.
But I want to know this info, so I put it as warning

2021-05-20 12:43 UTC, lalottacontinua commented on src/main/scala/com/ubirch/services/poc/PocAdminCreator.scala
> +    val spaceName = s"${pocConfig.teamDriveStage}_${tenant.tenantName.value}"
yeah, sorry. the requirements were not very well defined. ;)

2021-05-21 14:36 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/teamdrive/SttpTeamDriveClient.scala
> +            val errorMsg = s"couldn't find the space name: $spaceName"
yes, i throw error after call this method if it's None

2021-05-21 14:39 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/keycloak/users/KeycloakUserService.scala
>  trait KeycloakUserService {
This file is mainly affected.

2021-05-21 14:39 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/poc/CertfiyHelper.scala
> +trait CertifyHelper {
this file as well

2021-05-21 14:39 UTC, Hiroki6 commented on src/main/scala/com/ubirch/services/poc/PocAdminCreator.scala
> +object PocAdminCreator {
here as well

2021-05-21 14:43 UTC, Hiroki6 reviewed
main additional changes are below
- remove username from CertifyKeycloak
- inviteToTeamDrive field of PocAdminStatus became Option
- certifyUserId field of PocAdmin became Option and it's used in CertifyHelper

2021-05-21 16:37 UTC, lalottacontinua reviewed
nearly done. one important change required regarding assigning the tenantGroup to the poc-admin.

2021-05-21 16:37 UTC, lalottacontinua commented on src/main/scala/com/ubirch/services/keycloak/users/KeycloakUserService.scala
> +  override def addGroupToUserByUserId(
is there a difference between this and the previous method? I cannot find it.

2021-05-21 16:37 UTC, lalottacontinua commented on src/main/scala/com/ubirch/services/poc/CertfiyHelper.scala
> +      statusFinal <- addGroupByIdToCertify(userId, tenantGroupId).map {
this should be addGroupByName. I'm sorry, if I have miscommunicated this?! Or better, you retrieve the tenant.certifyGroupId and addGroupById.

2021-05-21 16:37 UTC, lalottacontinua commented on src/main/scala/com/ubirch/services/poc/PocAdminCreator.scala
> +      _ <- quillMonixJdbcContext.withTransaction {
nice!

2021-05-21 16:37 UTC, lalottacontinua commented on src/test/scala/com/ubirch/ModelCreationHelper.scala
> +    name: String = Random.alphanumeric.take(10).mkString,
make this an extra method? Random.alphanumeric.take(10).mkString,

2021-05-21 16:37 UTC, lalottacontinua commented on src/test/scala/com/ubirch/data/KeycloakTestData.scala
> +      FirstName(Random.alphanumeric.take(10).mkString("")),
same here? Random.alphanumeric.take(10).mkString, -> extra method.

2021-05-21 16:40 UTC, lalottacontinua commented on src/main/scala/com/ubirch/models/poc/PocAdminStatus.scala
> +  def init(podAdmin: PocAdmin, poc: Poc): PocAdminStatus = {
do you really need the poc as a parameter?

2021-05-21 17:43 UTC, lalottacontinua approved these changes

2021-05-21 17:44 UTC, merged